# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6108467123a3af30ee2025278a494f9f4e40c33f19ab68e3d55db3a9856cbe51e833bfb366dcc43dbec3b9f4db4e0e0263f1d7286bca5100bc0183a90b8e66cd

test:
  secret_key_base: d15281411a9ced1639b7c19e2a85c8332b4d60a01096da0a5b800fce27cdf9f353d59e0daa0b0ef8220cd843d575f32cd5b48ebd6ae10df0e3b8b10933d2f507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
